adding dispatch

diff --git a/.github/workflows/jest_test.yml b/.github/workflows/jest_test.yml
--- a/.github/workflows/jest_test.yml
+++ b/.github/workflows/jest_test.yml
@@ -9,6 +9,8 @@ on:
     branches:
       - main
 
+  workflow_dispatch:
+
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -29,4 +31,5 @@ jobs:
         run: npm install jest
 
       - name: Run tests
-        run: npm test
+        run: |
+          npm test || (echo "❌ Tests failed" && exit 1)
